repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: 'node_modules/'
      - id: end-of-file-fixer
        exclude: 'node_modules/'
